name: Build and Publish Executable

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write  # Grant write access to create releases

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --noconsole SketchPad.py
        
    - name: Create a Tag
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a v${{ github.run_number }} -m "Automated build tag"
        git push origin v${{ github.run_number }}

    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        tag: "v${{ github.run_number }}"  # Use the dynamically created tag
        artifacts: "dist/SketchPad.exe"
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "Release for build ${{ github.run_number }}"
        body: |
          Build for commit: ${{ github.sha }}
          - Branch: ${{ github.ref_name }}
          - Built by GitHub Actions.
        prerelease: true

